@YouTubeCatalog_Api_HostAddress = http://localhost:5042

POST {{YouTubeCatalog_Api_HostAddress}}/api/catalog/query
Content-Type: application/json
Accept: application/json

{
  "ChannelIds": ["UCwYzZs_hwA6NdaQp6Hjhe5w"],
  "Top": 20,
  "Days": 90
}
  
  
# Netflix "UCWOA1ZGywLbqmigxE4Qlvuw"
# TED "UCAuUUnT6oDeKwE6v1NGQxug"
# Trailer Feed "UCHQbbZQoEdMsLY1YizKxQFw"
# 20th Century Studios "UC2-BeLxzUBSs0uSrmzWhJuQ"
# ONE Media Coverage "UCwYzZs_hwA6NdaQp6Hjhe5w"
###